const token=localStorage.xytAuthToken||"",$=s=>document.querySelector(s),statusNames={active:"待兑换",used:"已兑换",revoked:"已撤销",expired:"已过期"},sourceNames={xiaohongshu:"小红书",xianyu:"闲鱼",offline:"线下",other:"其他"};let latestLink="";
async function api(url,options={}){const response=await fetch(url,{...options,headers:{"content-type":"application/json",...(options.headers||{}),authorization:`Bearer ${token}`}}),data=await response.json();if(!response.ok)throw new Error(data.error||"操作失败");return data}
const date=value=>value?new Date(value).toLocaleString("zh-CN"):"—",esc=value=>String(value??"").replace(/[&<>"']/g,char=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[char]));
async function load(){try{const {redemptions}=await api("/api/admin/redemptions");$("#redemptions").innerHTML=redemptions.length?redemptions.map(item=>`<article class="order admin-order"><div class="order-head"><div><b>${item.plan==='premium'?'高级会员':'月度会员'} · ${item.days}天</b><div class="muted">${sourceNames[item.source]||esc(item.source)}${item.platformOrderId?` · 订单 ${esc(item.platformOrderId)}`:''} · 尾码 ${esc(item.codeHint)}</div></div><span class="tag ${item.status}">${statusNames[item.status]||item.status}</span></div><div>创建：${date(item.createdAt)} · 有效至：${date(item.expiresAt)}</div>${item.customerNote?`<div>客户备注：${esc(item.customerNote)}</div>`:''}${item.user?`<div class="notice">兑换账号：${esc(item.user.phone||item.user.name)} · ${date(item.usedAt)}</div>`:''}<div class="actions">${item.status==='active'?`<button data-revoke="${item.id}">撤销链接</button>`:''}</div></article>`).join(""):"<p class='muted'>暂无兑换记录</p>";document.querySelectorAll("[data-revoke]").forEach(button=>button.onclick=()=>revoke(button.dataset.revoke))}catch(error){$("#redemptions").innerHTML=`<p>${esc(error.message)}。请使用管理员手机号登录。</p>`}}
async function create(event){event.preventDefault();try{const payload={plan:$("#plan").value,days:Number($("#days").value),source:$("#source").value,platformOrderId:$("#platformOrderId").value.trim(),customerNote:$("#customerNote").value.trim()};const {redemption,code}=await api("/api/admin/redemptions",{method:"POST",body:JSON.stringify(payload)});latestLink=`${location.origin}/membership.html?code=${encodeURIComponent(code)}`;$("#replyText").value=`您好，您的${redemption.plan==='premium'?'高级':'月度'}会员兑换链接已生成：\n${latestLink}\n\n请在72小时内打开，登录手机号账户后确认兑换。链接仅限一个账号使用，兑换成功后自动失效。\n如果平台无法打开链接，可复制兑换码：${code}`;$("#generated").classList.remove("hidden");await load()}catch(error){alert(error.message)}}
async function copyText(value){try{await navigator.clipboard.writeText(value);alert("已复制") }catch{const area=$("#replyText");area.focus();area.select();document.execCommand("copy");alert("已复制")}}
async function revoke(id){if(!confirm("确认撤销这条未使用的兑换链接？"))return;try{await api(`/api/admin/redemptions/${id}/revoke`,{method:"POST",body:"{}"});await load()}catch(error){alert(error.message)}}
function extractOrder(text){const clean=text.replace(/[ \t]+/g," "),compact=clean.replace(/\s/g,"");let source="other";if(/闲鱼|闲置|Goofish/i.test(clean))source="xianyu";else if(/小红书|RED|薯店/i.test(clean))source="xiaohongshu";const orderMatch=clean.match(/(?:订单号|订单编号|交易号|订单号码)\s*[：:]?\s*([A-Za-z0-9-]{6,})/i)||clean.match(/\b(\d{12,})\b/);const noteMatch=clean.match(/(?:买家|用户|客户|昵称|收货人)\s*[：:]?\s*([^\n]{2,24})/);let plan="monthly";if(/高级会员|20人|19[.,]?9/.test(compact))plan="premium";else if(/月度会员|6人|9[.,]?9/.test(compact))plan="monthly";let days=30;const dayMatch=clean.match(/(\d{1,3})\s*天/),monthMatch=clean.match(/(\d{1,2})\s*(?:个月|月)/);if(dayMatch)days=Math.min(365,Math.max(1,Number(dayMatch[1])));else if(monthMatch)days=Math.min(365,Number(monthMatch[1])*30);return{source,platformOrderId:orderMatch?orderMatch[1]:"",customerNote:noteMatch?noteMatch[1].trim().slice(0,100):"",plan,days}}
function fillOrder(fields){$("#source").value=fields.source;$("#plan").value=fields.plan;$("#days").value=fields.days;if(fields.platformOrderId)$("#platformOrderId").value=fields.platformOrderId;if(fields.customerNote)$("#customerNote").value=fields.customerNote}
async function recognizeScreenshot(input){const file=input.files[0];if(!file)return;if(file.size>8*1024*1024)return alert("截图不能超过8MB");const preview=$("#ocrPreview"),progress=$("#ocrProgress");preview.src=URL.createObjectURL(file);preview.classList.remove("hidden");progress.textContent="正在载入中文识别组件…";progress.classList.remove("hidden");if(!window.Tesseract){progress.textContent="识别组件载入失败，请检查网络后刷新页面";return}let worker;try{worker=await Tesseract.createWorker(["chi_sim","eng"],1,{logger:message=>{if(message.status==="recognizing text")progress.textContent=`正在识别文字 ${Math.round((message.progress||0)*100)}%`;else progress.textContent="正在准备识别…"}});const result=await worker.recognize(file),text=result.data.text||"";$("#ocrText").textContent=text;$("#ocrDetails").classList.remove("hidden");const fields=extractOrder(text);fillOrder(fields);progress.textContent=`识别完成${fields.platformOrderId?`，已找到订单号 ${fields.platformOrderId}`:"，未找到明确订单号，请核对后填写"}。请确认下方信息后再生成链接。`;document.querySelector("#createForm").scrollIntoView({behavior:"smooth"})}catch(error){progress.textContent=`识别失败：${error.message||"请换一张更清晰的截图"}`}finally{if(worker)await worker.terminate()}}
$("#orderScreenshot").onchange=event=>recognizeScreenshot(event.target);$("#createForm").onsubmit=create;$("#copyReply").onclick=()=>copyText($("#replyText").value);$("#copyLink").onclick=()=>copyText(latestLink);$("#refresh").onclick=load;load();
