const token=localStorage.xytAuthToken||"";let user=null,paymentConfig={};
const $=s=>document.querySelector(s),statusNames={pending:"待付款",submitted:"待审核",paid:"已开通",rejected:"已拒绝",refunded:"已退款"};
async function api(url,options={}){const response=await fetch(url,{...options,headers:{"content-type":"application/json",...(options.headers||{}),authorization:`Bearer ${token}`}}),data=await response.json();if(!response.ok)throw new Error(data.error||"操作失败");return data}
const date=value=>value?new Date(value).toLocaleString("zh-CN"):"—";
async function load(){if(!token){$("#orders").innerHTML='<p>请先返回首页登录手机号账户。</p>';return}try{user=(await api("/api/me")).user;$("#memberStatus").innerHTML=user.isAdmin?"平台管理员 · 永久免费":`${user.plan==='premium'?'高级会员':user.plan==='monthly'?'月度会员':'免费用户'}${user.planExpiresAt?` · 到期时间 <span class="expiry">${date(user.planExpiresAt)}</span>`:''}`;if(user.isAdmin)$("#adminLink").classList.remove("hidden");paymentConfig=await fetch("/api/payment-config").then(r=>r.json());await loadOrders()}catch(error){$("#orders").textContent=error.message}}
async function loadOrders(){const {orders}=await api("/api/orders");$("#orders").innerHTML=orders.length?orders.map(order=>`<article class="order"><div class="order-head"><div><b>${order.plan==='premium'?'高级会员':'月度会员'}</b><div class="muted">订单 ${order.id} · ${date(order.createdAt)}</div></div><span class="tag ${order.status}">${statusNames[order.status]||order.status}</span></div><div>¥${(order.amount/100).toFixed(1)}${order.reviewNote?` · ${order.reviewNote}`:''}</div><div class="actions">${['pending','rejected'].includes(order.status)?`<label class="file-label">上传付款截图<input hidden type="file" accept="image/png,image/jpeg,image/webp" data-proof="${order.id}"></label>`:''}${order.hasProof?`<button data-view="${order.id}">查看付款截图</button>`:''}</div></article>`).join(""):"<p class='muted'>暂无订单</p>";document.querySelectorAll("[data-proof]").forEach(input=>input.onchange=()=>uploadProof(input));document.querySelectorAll("[data-view]").forEach(button=>button.onclick=()=>viewProof(button.dataset.view))}
async function createOrder(plan){if(!token)return alert("请先返回首页登录");try{const {order}=await api("/api/orders",{method:"POST",body:JSON.stringify({plan})});$("#orderSummary").textContent=`${plan==='premium'?'高级会员 ¥19.9/月':'月度会员 ¥9.9/月'} · 订单号 ${order.id}`;$("#qrBox").innerHTML=paymentConfig.qrUrl?`<img src="${paymentConfig.qrUrl}" alt="微信收款码">`:"收款码尚未配置，请联系管理员";$("#payModal").classList.remove("hidden");await loadOrders()}catch(error){alert(error.message)}}
function uploadProof(input){const file=input.files[0];if(!file)return;if(file.size>2*1024*1024)return alert("图片不能超过2MB");const reader=new FileReader();reader.onload=async()=>{try{await api(`/api/orders/${input.dataset.proof}/proof`,{method:"POST",body:JSON.stringify({proofData:reader.result})});alert("已提交，等待管理员审核");loadOrders()}catch(error){alert(error.message)}};reader.readAsDataURL(file)}
async function viewProof(id){try{const {proof}=await api(`/api/orders/${id}/proof`);const win=window.open();win.document.write(`<img style="max-width:100%" src="${proof}">`)}catch(error){alert(error.message)}}
document.querySelectorAll("[data-plan]").forEach(button=>button.onclick=()=>createOrder(button.dataset.plan));$("#closePay").onclick=()=>$("#payModal").classList.add("hidden");load();
