const fs=require("fs"),path=require("path"),crypto=require("crypto");
const file=process.env.DATA_FILE||path.join(__dirname,"data","store.json");
function load(){try{const value=JSON.parse(fs.readFileSync(file,"utf8"));return{users:[],sessions:[],orders:[],redemptions:[],...value}}catch{return{users:[],sessions:[],orders:[],redemptions:[]}}}
const db=load();
const adminEmails=new Set((process.env.ADMIN_EMAILS||"1214532603@qq.com").split(",").map(v=>v.trim().toLowerCase()).filter(Boolean));
const adminPhones=new Set((process.env.ADMIN_PHONES||"19959217689").split(",").map(v=>v.replace(/\D/g,"")).filter(Boolean));
function normalizePhone(phone){return String(phone||"").replace(/\D/g,"")}
function isAdmin(user){return !!user&&(adminEmails.has(String(user.email||"").toLowerCase())||adminPhones.has(normalizePhone(user.phone)))}
function save(){fs.mkdirSync(path.dirname(file),{recursive:true});const temp=file+".tmp";fs.writeFileSync(temp,JSON.stringify(db,null,2));fs.renameSync(temp,file)}
function passwordHash(password,salt=crypto.randomBytes(16).toString("hex")){return{salt,hash:crypto.scryptSync(password,salt,64).toString("hex")}}
function expireUser(user){if(!isAdmin(user)&&user.planExpiresAt&&user.planExpiresAt<=Date.now()){user.plan="free";user.planExpiresAt=null;user.planSourceOrderId=null;user.planSourceRedemptionId=null;save()}}
function safeUser(user){expireUser(user);return{id:user.id,email:user.email||null,phone:user.phone||null,name:user.name,role:isAdmin(user)?"admin":"user",isAdmin:isAdmin(user),plan:isAdmin(user)?"admin":user.plan||"free",planExpiresAt:isAdmin(user)?null:user.planExpiresAt||null,createdAt:user.createdAt}}
function createUser({email,password,name}){email=String(email||"").trim().toLowerCase();if(db.users.some(u=>u.email===email))throw new Error("该邮箱已经注册");const pass=passwordHash(password);const user={id:crypto.randomUUID(),email,name:(name||"会员").trim().slice(0,12),...pass,plan:"free",planExpiresAt:null,createdAt:Date.now()};db.users.push(user);save();return safeUser(user)}
function createPhoneUser({phone,password,name}){phone=normalizePhone(phone);if(!/^1\d{10}$/.test(phone))throw new Error("请输入正确的11位手机号");if(String(password||"").length<8)throw new Error("密码至少需要8位");if(db.users.some(user=>normalizePhone(user.phone)===phone))throw new Error("该手机号已经注册");const pass=passwordHash(password);const user={id:crypto.randomUUID(),phone,name:(name||"会员").trim().slice(0,12),...pass,plan:"free",planExpiresAt:null,createdAt:Date.now()};db.users.push(user);save();return safeUser(user)}
function createSession(user){const token=crypto.randomBytes(32).toString("hex");db.sessions.push({token,userId:user.id,expiresAt:Date.now()+30*864e5});save();return{token,user:safeUser(user)}}
function login(email,password){const user=db.users.find(u=>u.email===String(email||"").trim().toLowerCase());if(!user)return null;const pass=passwordHash(password,user.salt);if(!crypto.timingSafeEqual(Buffer.from(pass.hash,"hex"),Buffer.from(user.hash,"hex")))return null;return createSession(user)}
function loginPhone(phone,password){phone=normalizePhone(phone);const user=db.users.find(item=>normalizePhone(item.phone)===phone);if(!user||!user.salt||!user.hash)return null;const pass=passwordHash(password,user.salt);if(!crypto.timingSafeEqual(Buffer.from(pass.hash,"hex"),Buffer.from(user.hash,"hex")))return null;return createSession(user)}
function userByPhone(phone){return db.users.find(user=>normalizePhone(user.phone)===normalizePhone(phone))||null}
function userByToken(token){const session=db.sessions.find(s=>s.token===token&&s.expiresAt>Date.now());const user=session&&db.users.find(u=>u.id===session.userId);if(!user)return null;expireUser(user);return isAdmin(user)?{...user,plan:"premium",isAdmin:true}:user}
function publicOrder(order){const user=db.users.find(u=>u.id===order.userId);const{proofData,...safeOrder}=order;return{...safeOrder,user:user?{name:user.name,phone:user.phone||null,email:user.email||null}:null,hasProof:!!proofData}}
function createOrder(userId,plan){const prices={monthly:990,premium:1990};if(!prices[plan])throw new Error("套餐不存在");const order={id:crypto.randomBytes(8).toString("hex").toUpperCase(),userId,plan,amount:prices[plan],status:"pending",createdAt:Date.now()};db.orders.push(order);save();return publicOrder(order)}
function submitProof(userId,orderId,{proofData,payerNote}){const order=db.orders.find(o=>o.id===orderId&&o.userId===userId);if(!order)throw new Error("订单不存在");if(!["pending","rejected"].includes(order.status))throw new Error("该订单当前无法提交审核");const note=String(payerNote||"").trim().slice(0,80);if(note.length<2)throw new Error("请填写付款人微信昵称或手机号后四位");if(proofData&&(!/^data:image\/(?:png|jpeg|webp);base64,/.test(proofData)||proofData.length>2800000))throw new Error("付款图片格式不正确");if(proofData)order.proofData=proofData;else delete order.proofData;order.payerNote=note;order.status="submitted";order.submittedAt=Date.now();delete order.reviewNote;save();return publicOrder(order)}
function listOrdersForUser(userId){return db.orders.filter(o=>o.userId===userId).sort((a,b)=>b.createdAt-a.createdAt).map(publicOrder)}
function listOrdersAdmin(){return [...db.orders].sort((a,b)=>b.createdAt-a.createdAt).map(publicOrder)}
function getProof(requester,orderId){const order=db.orders.find(o=>o.id===orderId);if(!order||(!isAdmin(requester)&&order.userId!==requester.id))return null;return order.proofData||null}
function reviewOrder(admin,orderId,action,note=""){if(!isAdmin(admin))throw new Error("仅管理员可操作");const order=db.orders.find(o=>o.id===orderId);if(!order)throw new Error("订单不存在");const user=db.users.find(u=>u.id===order.userId);if(!user)throw new Error("用户不存在");if(action==="approve"){if(order.status!=="paid"){const base=Math.max(Date.now(),user.planExpiresAt||0);user.plan=order.plan;user.planExpiresAt=base+30*864e5;user.planSourceOrderId=order.id;order.status="paid";order.paidAt=Date.now()}}else if(action==="reject"){order.status="rejected";order.rejectedAt=Date.now()}else if(action==="refund"){order.status="refunded";order.refundedAt=Date.now();if(user.planSourceOrderId===order.id){user.plan="free";user.planExpiresAt=null;user.planSourceOrderId=null}}else throw new Error("不支持的审核操作");order.reviewNote=String(note||"").trim().slice(0,120);order.reviewedBy=admin.id;save();return publicOrder(order)}
function activateOrder(orderId){const admin={id:"webhook",phone:[...adminPhones][0]};return reviewOrder(admin,orderId,"approve","支付回调自动确认")}
function hashCode(code){return crypto.createHash("sha256").update(String(code||"").trim()).digest("hex")}
function redemptionStatus(item){if(item.status==="used"||item.status==="revoked")return item.status;if(item.expiresAt<=Date.now())return"expired";return"active"}
function publicRedemption(item){const user=item.usedBy&&db.users.find(u=>u.id===item.usedBy);return{id:item.id,plan:item.plan,days:item.days,source:item.source,platformOrderId:item.platformOrderId||"",customerNote:item.customerNote||"",status:redemptionStatus(item),createdAt:item.createdAt,expiresAt:item.expiresAt,usedAt:item.usedAt||null,revokedAt:item.revokedAt||null,user:user?{name:user.name,phone:user.phone||null}:null,codeHint:item.codeHint}}
function createRedemption(admin,{plan,days,source,platformOrderId,customerNote}){if(!isAdmin(admin))throw new Error("仅管理员可操作");if(!["monthly","premium"].includes(plan))throw new Error("请选择会员套餐");days=Math.max(1,Math.min(365,Number(days)||30));source=String(source||"other").trim().slice(0,20);platformOrderId=String(platformOrderId||"").trim().slice(0,60);customerNote=String(customerNote||"").trim().slice(0,100);const code=crypto.randomBytes(24).toString("base64url"),item={id:crypto.randomBytes(8).toString("hex").toUpperCase(),codeHash:hashCode(code),codeHint:code.slice(-6),plan,days,source,platformOrderId,customerNote,status:"active",createdBy:admin.id,createdAt:Date.now(),expiresAt:Date.now()+72*36e5};db.redemptions.push(item);save();return{redemption:publicRedemption(item),code}}
function listRedemptions(admin){if(!isAdmin(admin))throw new Error("仅管理员可访问");return[...db.redemptions].sort((a,b)=>b.createdAt-a.createdAt).map(publicRedemption)}
function revokeRedemption(admin,id){if(!isAdmin(admin))throw new Error("仅管理员可操作");const item=db.redemptions.find(v=>v.id===id);if(!item)throw new Error("兑换链接不存在");if(redemptionStatus(item)!=="active")throw new Error("该兑换链接已无法撤销");item.status="revoked";item.revokedAt=Date.now();save();return publicRedemption(item)}
function redeemCode(userId,code){const item=db.redemptions.find(v=>v.codeHash===hashCode(code));if(!item)throw new Error("兑换码不存在或已经失效");if(redemptionStatus(item)!=="active")throw new Error("兑换码不存在或已经失效");const user=db.users.find(u=>u.id===userId);if(!user)throw new Error("请先登录");const base=Math.max(Date.now(),user.planExpiresAt||0);user.plan=item.plan;user.planExpiresAt=base+item.days*864e5;user.planSourceRedemptionId=item.id;item.status="used";item.usedBy=user.id;item.usedAt=Date.now();save();return{user:safeUser(user),redemption:publicRedemption(item)}}
module.exports={safeUser,isAdmin,createUser,login,createPhoneUser,loginPhone,createSession,userByPhone,userByToken,createOrder,submitProof,listOrdersForUser,listOrdersAdmin,getProof,reviewOrder,activateOrder,createRedemption,listRedemptions,revokeRedemption,redeemCode};
