const fs=require("fs"),path=require("path"),crypto=require("crypto");
const file=process.env.DATA_FILE||path.join(__dirname,"data","store.json");
function load(){try{const value=JSON.parse(fs.readFileSync(file,"utf8"));return{users:[],sessions:[],orders:[],...value}}catch{return{users:[],sessions:[],orders:[]}}}
const db=load();
const adminEmails=new Set((process.env.ADMIN_EMAILS||"1214532603@qq.com").split(",").map(v=>v.trim().toLowerCase()).filter(Boolean));
const adminPhones=new Set((process.env.ADMIN_PHONES||"19959217689").split(",").map(v=>v.replace(/\D/g,"")).filter(Boolean));
function normalizePhone(phone){return String(phone||"").replace(/\D/g,"")}
function isAdmin(user){return !!user&&(adminEmails.has(String(user.email||"").toLowerCase())||adminPhones.has(normalizePhone(user.phone)))}
function save(){fs.mkdirSync(path.dirname(file),{recursive:true});const temp=file+".tmp";fs.writeFileSync(temp,JSON.stringify(db,null,2));fs.renameSync(temp,file)}
function passwordHash(password,salt=crypto.randomBytes(16).toString("hex")){return{salt,hash:crypto.scryptSync(password,salt,64).toString("hex")}}
function expireUser(user){if(!isAdmin(user)&&user.planExpiresAt&&user.planExpiresAt<=Date.now()){user.plan="free";user.planExpiresAt=null;user.planSourceOrderId=null;save()}}
function safeUser(user){expireUser(user);return{id:user.id,email:user.email||null,phone:user.phone||null,name:user.name,role:isAdmin(user)?"admin":"user",isAdmin:isAdmin(user),plan:isAdmin(user)?"admin":user.plan||"free",planExpiresAt:isAdmin(user)?null:user.planExpiresAt||null,createdAt:user.createdAt}}
function createUser({email,password,name}){email=String(email||"").trim().toLowerCase();if(db.users.some(u=>u.email===email))throw new Error("该邮箱已经注册");const pass=passwordHash(password);const user={id:crypto.randomUUID(),email,name:(name||"会员").trim().slice(0,12),...pass,plan:"free",planExpiresAt:null,createdAt:Date.now()};db.users.push(user);save();return safeUser(user)}
function createPhoneUser({phone,password,name}){phone=normalizePhone(phone);if(!/^1\d{10}$/.test(phone))throw new Error("请输入正确的11位手机号");if(String(password||"").length<8)throw new Error("密码至少需要8位");if(db.users.some(user=>normalizePhone(user.phone)===phone))throw new Error("该手机号已经注册");const pass=passwordHash(password);const user={id:crypto.randomUUID(),phone,name:(name||"会员").trim().slice(0,12),...pass,plan:"free",planExpiresAt:null,createdAt:Date.now()};db.users.push(user);save();return safeUser(user)}
function createSession(user){const token=crypto.randomBytes(32).toString("hex");db.sessions.push({token,userId:user.id,expiresAt:Date.now()+30*864e5});save();return{token,user:safeUser(user)}}
function login(email,password){const user=db.users.find(u=>u.email===String(email||"").trim().toLowerCase());if(!user)return null;const pass=passwordHash(password,user.salt);if(!crypto.timingSafeEqual(Buffer.from(pass.hash,"hex"),Buffer.from(user.hash,"hex")))return null;return createSession(user)}
function loginPhone(phone,password){phone=normalizePhone(phone);const user=db.users.find(item=>normalizePhone(item.phone)===phone);if(!user||!user.salt||!user.hash)return null;const pass=passwordHash(password,user.salt);if(!crypto.timingSafeEqual(Buffer.from(pass.hash,"hex"),Buffer.from(user.hash,"hex")))return null;return createSession(user)}
function userByPhone(phone){return db.users.find(user=>normalizePhone(user.phone)===normalizePhone(phone))||null}
function userByToken(token){const session=db.sessions.find(s=>s.token===token&&s.expiresAt>Date.now());const user=session&&db.users.find(u=>u.id===session.userId);if(!user)return null;expireUser(user);return isAdmin(user)?{...user,plan:"premium",isAdmin:true}:user}
function publicOrder(order){const user=db.users.find(u=>u.id===order.userId);const{proofData,...safeOrder}=order;return{...safeOrder,user:user?{name:user.name,phone:user.phone||null,email:user.email||null}:null,hasProof:!!proofData}}
function createOrder(userId,plan){const prices={monthly:990,premium:1990};if(!prices[plan])throw new Error("套餐不存在");const order={id:crypto.randomBytes(8).toString("hex").toUpperCase(),userId,plan,amount:prices[plan],status:"pending",createdAt:Date.now()};db.orders.push(order);save();return publicOrder(order)}
function submitProof(userId,orderId,{proofData,payerNote}){const order=db.orders.find(o=>o.id===orderId&&o.userId===userId);if(!order)throw new Error("订单不存在");if(!["pending","rejected"].includes(order.status))throw new Error("该订单当前无法提交凭证");if(!/^data:image\/(?:png|jpeg|webp);base64,/.test(proofData||"")||proofData.length>2800000)throw new Error("请上传不超过2MB的PNG、JPG或WebP图片");order.proofData=proofData;order.payerNote=String(payerNote||"").trim().slice(0,80);order.status="submitted";order.submittedAt=Date.now();delete order.reviewNote;save();return publicOrder(order)}
function listOrdersForUser(userId){return db.orders.filter(o=>o.userId===userId).sort((a,b)=>b.createdAt-a.createdAt).map(publicOrder)}
function listOrdersAdmin(){return [...db.orders].sort((a,b)=>b.createdAt-a.createdAt).map(publicOrder)}
function getProof(requester,orderId){const order=db.orders.find(o=>o.id===orderId);if(!order||(!isAdmin(requester)&&order.userId!==requester.id))return null;return order.proofData||null}
function reviewOrder(admin,orderId,action,note=""){if(!isAdmin(admin))throw new Error("仅管理员可操作");const order=db.orders.find(o=>o.id===orderId);if(!order)throw new Error("订单不存在");const user=db.users.find(u=>u.id===order.userId);if(!user)throw new Error("用户不存在");if(action==="approve"){if(order.status!=="paid"){const base=Math.max(Date.now(),user.planExpiresAt||0);user.plan=order.plan;user.planExpiresAt=base+30*864e5;user.planSourceOrderId=order.id;order.status="paid";order.paidAt=Date.now()}}else if(action==="reject"){order.status="rejected";order.rejectedAt=Date.now()}else if(action==="refund"){order.status="refunded";order.refundedAt=Date.now();if(user.planSourceOrderId===order.id){user.plan="free";user.planExpiresAt=null;user.planSourceOrderId=null}}else throw new Error("不支持的审核操作");order.reviewNote=String(note||"").trim().slice(0,120);order.reviewedBy=admin.id;save();return publicOrder(order)}
function activateOrder(orderId){const admin={id:"webhook",phone:[...adminPhones][0]};return reviewOrder(admin,orderId,"approve","支付回调自动确认")}
module.exports={safeUser,isAdmin,createUser,login,createPhoneUser,loginPhone,createSession,userByPhone,userByToken,createOrder,submitProof,listOrdersForUser,listOrdersAdmin,getProof,reviewOrder,activateOrder};
